name: End-to-end tests 🧪
on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress comando line
        default: npx cypress run
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        run: ${{ github.event.inputs.cli }}
