name: End-to-end tests 🧪
on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress comando line
        default: npx cypress run
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: actions/checkout@v4.1.1
